### ISSUE TITLE
Class 'Metaregistrar\EPP\eppDnssecInfoDomainResponse' not found

### ISSUE THREAD

**Issue by K1ll3rM** [metaregistrar/php-epp-client#124]
When I try to infodomain.php example using rrpproxy I get the error: 
Fatal error: Uncaught Error: Class 'Metaregistrar\EPP\eppDnssecInfoDomainResponse' not found in C:\xampp\htdocs\SIDN\libraries\php-epp-client-1.0.4\Protocols\EPP\eppConnection.php on line 800

I have tried including the dnssec extension before hand but that just results in a silent crash of the script.

Is this a bug or am I doing something very wrong?

**Comment by metaregistrar** [comment]
In rrpproxyEppConnection/eppConnection.php, did you use "parent::enableDnssec();"

This command includes Protocols/EPP/eppExtensions/secDNS-1.1/includes.php, where this function is included.

Please make sure you have the latest version.

**Comment by K1ll3rM** [comment]
@metaregistrar I just downloaded 1.0.4 and I have not changed that file. I do see that enableDnssec() is called in there. The only thing I changed is that I have added an .ini file for the settings. It also works with the domain name check so the settings aren't the problem

**Comment by metaregistrar** [comment]
i will test this behaviour with key-systems and find the problem.

**Comment by K1ll3rM** [comment]
Alright, thank you for the fast responses!

**Comment by K1ll3rM** [comment]
I'm using the infodomain.php in examples with the command "php infodomain.php testing.com". The only thing that I have changed in that file is give a settings.ini with the create() function.
That ini looks roughly like this:
interface=rrpproxyEppConnection
hostname=ssl://epp-ote.rrpproxy.net
port=1700
userid=XXXXX
password=XXXXXXXXX

Note that I'm using PHP 7.1 but I don't see how that would be relevant with this type of error

**Comment by metaregistrar** [comment]
I was able to reproduce your error using the infodomain.php script in the Examples directory. Will start debugging now.

**Comment by K1ll3rM** [comment]
Alright, thank you very much in advance!

**Comment by metaregistrar** [comment]
The problem is solved in the latest version. Please note that i also made a small change to infodomain.php because it did not report any error back correctly.

**Comment by K1ll3rM** [comment]
Ok thank you very much, I'll update right away.

**Comment by K1ll3rM** [comment]
@metaregistrar I tried it out again but now I'm getting the message: "ERROR: Error 2303: Object does not exist" So I still do not get a response.

**Comment by metaregistrar** [comment]
Are you sure the requested domain name exists with RRPPROXY? This looks like a legitimate error.

**Comment by K1ll3rM** [comment]
I've just tried it with one that was registered with rrpproxy and it returns the same error

**Comment by metaregistrar** [comment]
Are you sure the domain name is present on the OTE system? 

I tried infodomain.php with a generic test domainname and it returns:
Retrieving info on x65qtvs9qeztxq92z9f9.nl
Info domain for x65qtvs9qeztxq92z9f9.nl:
Created on 2017-12-06T14:29:18.0000Z
Last update on 2017-12-06T14:29:18.0000Z
Registrant P-TRN4346
Contact info:
  admin: P-TRN4346
  tech: P-TRN4346
  billing: P-TRN4346
Nameserver info:

**Comment by K1ll3rM** [comment]
How do I check that? When I try your domain it returns 2201. I'm sorry if there is anything I'm not getting at all, I'm quite new to all of this

**Comment by metaregistrar** [comment]
You should login to the OTE system of Key-Systems and see which domain names are already registered. 

https://wi-ote.rrpproxy.net/

**Comment by K1ll3rM** [comment]
It works now thank you! I hadn't realized that the test server didn't have all domain names on it already.

**Comment by Mops7132** [comment]
I have downloaded the latest version for php 8 but I have the same issue. Can anyone help me?
